name: test

on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bewuethr/shellcheck-action@v2

  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mig4/setup-bats@v1
      - uses: brokenpip3/setup-bats-libs@0.1.0
        with:
          support-path: ${{ github.workspace }}/test/test_helper/bats-support
          assert-path: ${{ github.workspace }}/test/test_helper/bats-assert
      - run: bats test
